version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.22.4
    container_name: temporal-dev
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DB=sqlite
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/development.yaml
    volumes:
      - ./temporal-data:/var/temporal

  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: temporal-ui
    depends_on:
      - temporal
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.4
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    stdin_open: true
    tty: true
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233